name: Auto Commit

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "tagizadeorxan"
          git config --global user.email "tagizade.orxan@gmail.com"

      - name: Make changes and push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo "Auto commit on $(date)" >> activity_log.txt
          git add activity_log.txt
          git commit -m "Automated commit: $(date)"
          git push https://tagizadeorxan:${GH_PAT}@github.com/tagizadeorxan/workflow.git main
